name: "Main Branch: Web"

on:
  push:
    branches:
      - main
    paths:
      - "web/**"
      - ".prettierrc"
      - ".github/workflows/main_web.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"
          cache-dependency-path: "web/package-lock.json"

      - name: Install dependencies
        working-directory: web
        run: npm install

      - name: Lint check
        working-directory: web
        run: npm run format-check

      - name: Build (test)
        working-directory: web
        env:
          VUE_APP_FIREBASE_API_KEY: ${{ secrets.TEST_FIREBASE_API_KEY }}
          VUE_APP_FIREBASE_PROJECT: ${{ secrets.TEST_GCLOUD_PROJECT }}
          VUE_APP_WEB_URL: "https://test.110yards.ca"
          VUE_APP_API_110_YARDS_URL: "https://api.test.110yards.ca"
        run: npm run build:test

      - name: Deploy (test)
        working-directory: web
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          TARGET_PROJECT: ${{ secrets.TEST_GCLOUD_PROJECT }}
        run: |
          npm install -g firebase-tools
          firebase deploy --only hosting --token $FIREBASE_TOKEN --project $TARGET_PROJECT

      - name: Build (live)
        working-directory: web
        env:
          VUE_APP_FIREBASE_API_KEY: ${{ secrets.LIVE_FIREBASE_API_KEY }}
          VUE_APP_FIREBASE_PROJECT: ${{ secrets.LIVE_GCLOUD_PROJECT }}
          VUE_APP_WEB_URL: "https://110yards.ca"
          VUE_APP_API_110_YARDS_URL: "https://api.110yards.ca"
        run: npm run build:test

      - name: Deploy (live)
        working-directory: web
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          TARGET_PROJECT: ${{ secrets.LIVE_GCLOUD_PROJECT }}
        run: firebase deploy --only hosting --token $FIREBASE_TOKEN --project $TARGET_PROJECT
