name: "Pull Request: Rules"

on:
  pull_request:
    paths:
      - "firestore.rules"
      - ".github/workflows/pr_rules.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          TARGET_PROJECT: ${{ secrets.TEST_GCLOUD_PROJECT }}
        run: |
          npm install -g firebase-tools
          firebase deploy --only firestore:rules --token $FIREBASE_TOKEN --project $TARGET_PROJECT