steps:
  - name: "gcr.io/cloud-builders/gcloud"
    id: "functions deploy data_importer"
    args:
      [
        "functions",
        "deploy",
        "data_importer",
        "--gen2"
        "--trigger-topic",
        "topic_import_data",
        "--runtime",
        "python310",
        "--entry-point=data_importer",
        --update-env-vars=GCLOUD_PROJECT=$_TARGET_PROJECT_ID",
        "--update-secrets=CFL_API_KEY=CFL_API_KEY:latest",
      ]
