steps:
  - name: "gcr.io/cloud-builders/gcloud"
    id: "functions deploy league_counter"
    args: ["functions", "deploy", "league_counter", 
            "--trigger-event", "providers/cloud.firestore/eventTypes/document.create",
            "--trigger-resource", "projects/$PROJECT_ID/databases/(default)/documents/league/{league_id}",
            "--retry",
            "--runtime", "python38",
            "--entry-point=update_league_count"
        ]