apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  ports:
    - port: 3000
  selector:
    name: api
status:
  loadBalancer: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: api
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      name: api
  strategy: {}
  template:
    metadata:
      labels:
        name: api
    spec:
      containers:
        - image: api
          name: api
          ports:
            - containerPort: 3000
          env:
            - name: DEV
              value: "true"
            - name: FIREBASE_API_KEY
              valueFrom:
                configMapKeyRef:
                  name: environment
                  key: FIREBASE_API_KEY
            - name: ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: environment
                  key: API_ENDPOINT
            - name: GCLOUD_PROJECT
              valueFrom:
                configMapKeyRef:
                  name: environment
                  key: GCLOUD_PROJECT
            - name: ORIGINS
              valueFrom:
                configMapKeyRef:
                  name: environment
                  key: ORIGINS
            - name: FIRESTORE_EMULATOR_HOST
              valueFrom:
                configMapKeyRef:
                  name: environment
                  key: FIRESTORE_EMULATOR_HOST
            - name: RTDB_EMULATOR_HOST
              valueFrom:
                configMapKeyRef:
                  name: environment
                  key: RTDB_EMULATOR_HOST
            - name: FIREBASE_AUTH_EMULATOR_HOST
              valueFrom:
                configMapKeyRef:
                  name: environment
                  key: FIREBASE_AUTH_EMULATOR_HOST

          resources: {}
      restartPolicy: Always
status: {}
