# generated by datamodel-codegen:
#   filename:  event_status.json
#   timestamp: 2021-03-19T11:37:34+00:00

from __future__ import annotations
from typing import Optional

from pydantic import BaseModel

EVENT_STATUS_PRE_GAME = 1
EVENT_STATUS_IN_PROGRESS = 2
EVENT_STATUS_FINAL = 4
EVENT_STATUS_POSTPONED = 6
EVENT_STATUS_CANCELLED = 9


class EventStatus(BaseModel):
    event_status_id: int
    name: str
    is_active: bool
    quarter: int
    minutes: Optional[int]
    seconds: Optional[int]
    down: Optional[int]
    yards_to_go: Optional[int]

    def has_started(self) -> bool:
        if self.event_status_id in [EVENT_STATUS_IN_PROGRESS, EVENT_STATUS_FINAL]:
            return True
        else:
            return False
