name: "Python - CI"

inputs:
  WORKING_DIRECTORY:
    required: true

runs:
  using: composite

  steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install dependencies
      shell: bash
      run: .scripts/common/install-dependencies-service.sh ${{ inputs.WORKING_DIRECTORY }}

    - name: Run checks
      shell: bash
      run: .scripts/python/checks.sh ${{ inputs.WORKING_DIRECTORY }}
