FROM python:3.10

RUN mkdir /app

RUN pip install debugpy

COPY requirements.txt /requirements.txt
COPY dev.py /dev.py

RUN pip install --no-cache-dir --upgrade -r requirements.txt

COPY ./app /app

CMD uvicorn app.main:app --host 0.0.0.0 --port 3000
