# generated by datamodel-codegen:
#   filename:  event_type.json
#   timestamp: 2021-03-19T11:37:46+00:00

from __future__ import annotations

from pydantic import BaseModel

EVENT_TYPE_PRESEASON = 0
EVENT_TYPE_REGULAR = 1
EVENT_TYPE_PLAYOFFS = 2
EVENT_TYPE_GREY_CUP = 3
EVENT_TYPE_EXHIBITION = 4


class EventType(BaseModel):
    event_type_id: int
    name: str
    title: str
