# generated by datamodel-codegen:
#   filename:  game_score.json
#   timestamp: 2021-03-19T11:38:02+00:00

from __future__ import annotations

from pydantic import BaseModel


class GameScore(BaseModel):
    away: int
    home: int
