name: "Continuous Integration"

on:
  pull_request:
    paths-ignore:
      - "**/*.md"

  push:
    branches:
      - develop

    paths-ignore:
      - "**/*.md"

jobs:
  changes:
    name: Calculate changes
    runs-on: ubuntu-latest

    outputs:
      web: ${{ steps.changes.outputs.web }}
      api: ${{ steps.changes.outputs.api }}
      importer: ${{ steps.changes.outputs.importer }}
      system: ${{ steps.changes.outputs.system }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Calculate path changes
        uses: mdryden/paths-filter@4067d885736b84de7c414f582ac45897079b0a78
        id: changes
        with:
          # To add a new service to CI, you must add an filter here:
          filters: |
            web:
              - "web/**"
            api:
              - "services/api/**"
            importer:
              - "services/importer/**"
            system:
              - "services/system/**"
