name: "Main Branch: Web"

on:
  push:
    branches:
      - main
    paths:
      - "web/**"
      - ".prettierrc"
      - ".github/workflows/main_web.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: "web/package-lock.json"

      - name: Install dependencies
        working-directory: web
        run: npm install

      - name: Lint check
        working-directory: web
        run: npm run format-check

      - name: Build (test)
        working-directory: web
        env:
          VUE_APP_FIREBASE_API_KEY: ${{ secrets.TEST_FIREBASE_API_KEY }}
          VUE_APP_FIREBASE_PROJECT: ${{ secrets.TEST_GCLOUD_PROJECT }}
          VUE_APP_WEB_URL: "https://fantasy.test.110yards.ca"
          VUE_APP_API_110_YARDS_URL: "https://api.fantasy.test.110yards.ca"
        run: npm run build:test

      - name: Deploy (test)
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseServiceAccount: ${{ secrets.TEST_GCLOUD_CREDENTIALS }}
          projectId: ${{ secrets.TEST_GCLOUD_PROJECT }}
          channelId: live

      - name: Build (live)
        working-directory: web
        env:
          VUE_APP_FIREBASE_API_KEY: ${{ secrets.LIVE_FIREBASE_API_KEY }}
          VUE_APP_FIREBASE_PROJECT: ${{ secrets.LIVE_GCLOUD_PROJECT }}
          VUE_APP_WEB_URL: "https://fantasy.110yards.ca"
          VUE_APP_API_110_YARDS_URL: "https://api.fantasy.110yards.ca"
        run: npm run build:test

      - name: Deploy (live)
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseServiceAccount: ${{ secrets.LIVE_GCLOUD_CREDENTIALS }}
          projectId: ${{ secrets.LIVE_GCLOUD_PROJECT }}
          channelId: live
