name: "Web - CI"

runs:
  using: "composite"

  steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: "16"
        cache: "npm"
        cache-dependency-path: "web/package-lock.json"

    - name: Install dependencies
      working-directory: web
      shell: bash
      run: npm install

    - name: Lint check
      working-directory: web
      shell: bash
      run: npm run format-check

    - name: Build
      working-directory: web
      env:
        VUE_APP_WEB_URL: "https://test.110yards.ca"
        VUE_APP_API_110_YARDS_URL: "https://api.test.110yards.ca"
      shell: bash
      run: npm run build:test
